### ISSUE TITLE
스위트샵 빌더패턴 기능 구현

### ISSUE THREAD

**Issue by JiMinL03** [jaejin9771/Movie-Reservation-System#13]
## 📝 Description
주문내역을 빌더패턴을 사용하여 DTO로 전달하고 결제내역에서 DTO를 사용하도록 한다.

## 📍 Todo
- [x] 빌더패턴을 사용하여 DTO에 저장한다.
- [x] DTO에서 데이터를 가져와 총 가격을 계산한다
- [x] 스위트샵 화면에 가격 설명한다.

## 📢 To Reviewers
@jaejin9771
