### ISSUE TITLE
파일 입출력 일반화 코드 구현

### ISSUE THREAD

**Issue by jaejin9771** [jaejin9771/Movie-Reservation-System#17]
## 📝 Description
파일 입출력을 일반화 하기 위한 클래스들 구현

## 📍 Todo
- [x] CrudRepository 클래스 구현
- [x] 관련 Dto, Repository, 클래스 구현
- [x] 빌더 패턴 적용

## 📢 To Reviewers
@JiMinL03
