### ISSUE TITLE
주문내역 확인 기능 구현

### ISSUE THREAD

**Issue by JiMinL03** [jaejin9771/Movie-Reservation-System#25]
## 📝 Description
스위트샵 주문내역 확인 기능 구현

## 📍 Todo
- [x] 스위트샵 파일 내용 출력
- [x] 파일로부터 읽어온 데이터들을 JTable에 입력
- [x] getOrderList() split 필요

## 📢 To Reviewers
@jaejin9771
