### ISSUE TITLE
영화 클래스 수정 및 관련 뷰 생성

### ISSUE THREAD

**Issue by jaejin33** [jaejin9771/Movie-Reservation-System#30]
## 📝 Description
영화 등록 방식을 수정한다.
등록하면서 날짜, 시간, 상영관 등을 고르도록 한다.

## 📍 Todo
- [x] Movie클래스 속성 추가
- [x] 다른 관련 클래스들 수정
- [x] 영화 등록 뷰 구현

## 📢 To Reviewers
@JiMinL03
