### ISSUE TITLE
주문내역 영수증 출력 기능 구현중

### ISSUE THREAD

**Issue by JiMinL03** [jaejin9771/Movie-Reservation-System#37]
## 📝 Description
스위트샵 결제 완료 후 영수증 출력 화면으로 넘어갈 수 있다.
화면에선 이전에 결제한 주문내역이 뜨게 된다.
출력 버튼을 누르면 폴더에 영수증 형태의 txt 파일이 생기게 된다.

## 📍 Todo
- [x] 영수증 출력 화면 생성
- [x] 주문내역을 불러와 영수증 형태의 StringBuilder 구현
- [ ] 영수증 출력 요청이 들어오면 파일 입력 기능 구현

## 📢 To Reviewers
@jaejin9771
