### ISSUE TITLE
영화 상영정보 등록 기능 구현

### ISSUE THREAD

**Issue by jaejin9771** [jaejin9771/Movie-Reservation-System#49]
## 📝 Description
영화 정보를 토대로 상영관, 상영일시를 등록하는 기능을 구현한다.

## 📍 Todo
- [x] 상영정보 클래스 구현
- [x] 관련 클래스들 구현
- [x] 관리자 패키지 화면 추가 구현

## 📢 To Reviewers
@JiMinL03
