### ISSUE TITLE
영화 예매 기능 및 상영정보 삭제 구현

### ISSUE THREAD

**Issue by jaejin9771** [jaejin9771/Movie-Reservation-System#58]
## 📝 Description
영화를 예매하는 기능을 구현한다.
영화 상영정보를 삭제하는 기능을 구현한다.
## 📍 Todo
- [x] 영화 예매 내역 클래스를 만들어준다
- [x] 관련 클래스들을 생성 및 구현한다.
- [x] 삭제 로직을 구현한다.

## 📢 To Reviewers
@JiMinL03
